import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "@/components/layout/Navbar";
import { Footer } from "@/components/layout/Footer";

export const metadata: Metadata = {
  title: "SWE Job Prep | AI-Powered Interview Prep for FAANG & AI Startups",
  description:
    "Real job listings from top AI companies with personalized coding plans, system design guides, behavioral prep, and salary intelligence — generated by Claude Opus.",
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <body className="min-h-screen flex flex-col bg-slate-50">
        <Navbar />
        <main className="flex-1">{children}</main>
        <Footer />
      </body>
    </html>
  );
}
