"""
Company registry — 31 companies (11 FAANG++ + 20 AI Startups).
Board IDs that 404 at fetch time are silently skipped.
"""

COMPANY_REGISTRY: list[dict] = [
    # ── FAANG++ ──────────────────────────────────────────────────────────────
    {
        "name": "Google",
        "slug": "google",
        "ats_type": "greenhouse",
        "board_id": "google",
        "tier": "faang_plus",
        "hq": "Mountain View, CA",
        "size": "180,000+",
        "logo_url": "https://logo.clearbit.com/google.com",
        "about": "Alphabet subsidiary. World's dominant search engine, cloud, and AI research.",
        "loop_desc": "Phone screen → 4-5 virtual onsite rounds (2 coding, 1 system design, 1 behavioral, 1 Googleyness)",
        "comp_range": "L4: $280k–$350k | L5: $380k–$500k | L6: $500k–$700k | L7: $700k–$1M+",
    },
    {
        "name": "Meta",
        "slug": "meta",
        "ats_type": "greenhouse",
        "board_id": "meta",
        "tier": "faang_plus",
        "hq": "Menlo Park, CA",
        "size": "75,000+",
        "logo_url": "https://logo.clearbit.com/meta.com",
        "about": "Social media, VR/AR, and AI research powerhouse (Facebook, Instagram, WhatsApp).",
        "loop_desc": "Recruiter screen → coding phone screen → 4-5 onsite (2 coding, 1 system design, 1 behavioral, 1 cross-functional)",
        "comp_range": "E4: $260k–$320k | E5: $380k–$480k | E6: $520k–$700k | E7: $800k+",
    },
    {
        "name": "Amazon",
        "slug": "amazon",
        "ats_type": "greenhouse",
        "board_id": "amazon",
        "tier": "faang_plus",
        "hq": "Seattle, WA",
        "size": "1,500,000+",
        "logo_url": "https://logo.clearbit.com/amazon.com",
        "about": "E-commerce, AWS cloud, Alexa, Kuiper, and Zoox. LP-driven culture.",
        "loop_desc": "Online assessment → phone screen → 4-5 onsite (coding + system design + LP-heavy behavioral + bar raiser)",
        "comp_range": "SDE2: $200k–$280k | SDE3: $300k–$420k | Principal: $450k–$650k",
    },
    {
        "name": "Apple",
        "slug": "apple",
        "ats_type": "greenhouse",
        "board_id": "apple",
        "tier": "faang_plus",
        "hq": "Cupertino, CA",
        "size": "160,000+",
        "logo_url": "https://logo.clearbit.com/apple.com",
        "about": "Consumer devices, macOS/iOS, Silicon, and Services. Privacy-first culture.",
        "loop_desc": "Recruiter screen → technical phone screen → 4-6 onsite rounds (deep technical + cross-functional)",
        "comp_range": "ICT3: $220k–$290k | ICT4: $310k–$420k | ICT5: $450k–$600k | ICT6: $650k+",
    },
    {
        "name": "Netflix",
        "slug": "netflix",
        "ats_type": "greenhouse",
        "board_id": "netflix",
        "tier": "faang_plus",
        "hq": "Los Gatos, CA",
        "size": "13,000+",
        "logo_url": "https://logo.clearbit.com/netflix.com",
        "about": "Streaming giant. Freedom & Responsibility culture. All senior engineers.",
        "loop_desc": "Recruiter call → technical screen → 5-6 onsite rounds (system design emphasis, culture fit heavy)",
        "comp_range": "Senior: $450k–$900k all-cash (Netflix pays top-of-market, cash only)",
    },
    {
        "name": "Microsoft",
        "slug": "microsoft",
        "ats_type": "greenhouse",
        "board_id": "microsoft",
        "tier": "faang_plus",
        "hq": "Redmond, WA",
        "size": "220,000+",
        "logo_url": "https://logo.clearbit.com/microsoft.com",
        "about": "Azure, Office 365, GitHub, and heavy AI investment via OpenAI partnership.",
        "loop_desc": "Phone screen → 4-5 onsite (coding, system design, behavioral, as-appropriate)",
        "comp_range": "SDE2: $210k–$290k | SDE3: $300k–$420k | Principal: $450k–$650k",
    },
    {
        "name": "Nvidia",
        "slug": "nvidia",
        "ats_type": "greenhouse",
        "board_id": "nvidia",
        "tier": "faang_plus",
        "hq": "Santa Clara, CA",
        "size": "30,000+",
        "logo_url": "https://logo.clearbit.com/nvidia.com",
        "about": "GPU, CUDA, and AI infrastructure. Critical for every AI workload.",
        "loop_desc": "Recruiter screen → 2-3 technical phone screens → 4-5 onsite (deep systems, GPU programming)",
        "comp_range": "Senior: $380k–$550k | Staff: $550k–$800k | Principal: $800k+",
    },
    {
        "name": "OpenAI",
        "slug": "openai",
        "ats_type": "greenhouse",
        "board_id": "openai",
        "tier": "faang_plus",
        "hq": "San Francisco, CA",
        "size": "2,000+",
        "logo_url": "https://logo.clearbit.com/openai.com",
        "about": "Creator of GPT-4, ChatGPT, DALL-E, Codex. AGI-focused lab.",
        "loop_desc": "Recruiter screen → technical screen → 4-5 onsite (coding, ML systems, open-ended research discussion)",
        "comp_range": "Senior: $500k–$800k | Staff: $700k–$1.2M (large equity grants)",
    },
    {
        "name": "Anthropic",
        "slug": "anthropic",
        "ats_type": "greenhouse",
        "board_id": "anthropic",
        "tier": "faang_plus",
        "hq": "San Francisco, CA",
        "size": "1,000+",
        "logo_url": "https://logo.clearbit.com/anthropic.com",
        "about": "AI safety company, creator of Claude. Constitutional AI approach.",
        "loop_desc": "Recruiter screen → technical take-home → 3-4 onsite (systems, coding, values alignment)",
        "comp_range": "Senior: $450k–$700k | Staff: $650k–$1M+ (mission-driven equity)",
    },
    {
        "name": "DeepMind",
        "slug": "deepmind",
        "ats_type": "greenhouse",
        "board_id": "deepmind",
        "tier": "faang_plus",
        "hq": "London, UK",
        "size": "3,000+",
        "logo_url": "https://logo.clearbit.com/deepmind.com",
        "about": "Google's AI research lab. AlphaFold, Gemini, AlphaCode, AlphaStar.",
        "loop_desc": "Recruiter screen → technical screens → 4-5 onsite (ML research-heavy, coding, systems)",
        "comp_range": "Senior: $350k–$600k (UK-adjusted) | Research: $400k–$750k",
    },
    {
        "name": "xAI",
        "slug": "xai",
        "ats_type": "greenhouse",
        "board_id": "xai",
        "tier": "faang_plus",
        "hq": "San Francisco, CA",
        "size": "500+",
        "logo_url": "https://logo.clearbit.com/x.ai",
        "about": "Elon Musk's AI company, creator of Grok. Fast-moving, high-ownership.",
        "loop_desc": "Informal screen → 2-3 technical rounds (systems, coding, Grok architecture discussion)",
        "comp_range": "Senior: $400k–$700k | Staff: $600k–$1M+ (early-stage equity upside)",
    },

    # ── AI Startups ───────────────────────────────────────────────────────────
    {
        "name": "Mistral AI",
        "slug": "mistral-ai",
        "ats_type": "greenhouse",
        "board_id": "mistralai",
        "tier": "ai_startup",
        "hq": "Paris, France",
        "size": "200+",
        "logo_url": "https://logo.clearbit.com/mistral.ai",
        "about": "European open-weight LLM company. Mistral 7B, Mixtral MoE.",
        "loop_desc": "Technical screen → 3-4 rounds (ML systems, coding, research discussion)",
        "comp_range": "Senior: €150k–€250k + equity | Staff: €250k–€400k",
    },
    {
        "name": "Cohere",
        "slug": "cohere",
        "ats_type": "greenhouse",
        "board_id": "cohere",
        "tier": "ai_startup",
        "hq": "Toronto, CA",
        "size": "500+",
        "logo_url": "https://logo.clearbit.com/cohere.com",
        "about": "Enterprise NLP platform. Command R+, Rerank, Embed APIs.",
        "loop_desc": "Recruiter screen → technical screen → 4 onsite rounds",
        "comp_range": "Senior: $280k–$420k | Staff: $400k–$600k",
    },
    {
        "name": "Scale AI",
        "slug": "scale-ai",
        "ats_type": "greenhouse",
        "board_id": "scaleai",
        "tier": "ai_startup",
        "hq": "San Francisco, CA",
        "size": "1,500+",
        "logo_url": "https://logo.clearbit.com/scale.com",
        "about": "AI data infrastructure. Training data, RLHF, model evaluation.",
        "loop_desc": "Phone screen → 4-5 onsite rounds (coding, system design, product sense)",
        "comp_range": "Senior: $300k–$450k | Staff: $450k–$650k",
    },
    {
        "name": "Hugging Face",
        "slug": "hugging-face",
        "ats_type": "greenhouse",
        "board_id": "huggingface",
        "tier": "ai_startup",
        "hq": "New York, NY",
        "size": "300+",
        "logo_url": "https://logo.clearbit.com/huggingface.co",
        "about": "The GitHub for ML. Transformers library, Hub, Spaces, Inference API.",
        "loop_desc": "Async/technical take-home → 3-4 rounds (ML, open source contributions discussed)",
        "comp_range": "Senior: $250k–$400k | Staff: $380k–$550k",
    },
    {
        "name": "Runway",
        "slug": "runway",
        "ats_type": "greenhouse",
        "board_id": "runwayml",
        "tier": "ai_startup",
        "hq": "New York, NY",
        "size": "200+",
        "logo_url": "https://logo.clearbit.com/runwayml.com",
        "about": "Generative AI for video and creative tools. Gen-2, Gen-3 video models.",
        "loop_desc": "Recruiter screen → technical screen → 3-4 onsite",
        "comp_range": "Senior: $280k–$420k | Staff: $400k–$600k",
    },
    {
        "name": "Perplexity",
        "slug": "perplexity",
        "ats_type": "greenhouse",
        "board_id": "perplexityai",
        "tier": "ai_startup",
        "hq": "San Francisco, CA",
        "size": "200+",
        "logo_url": "https://logo.clearbit.com/perplexity.ai",
        "about": "AI-native search engine. Answer engine replacing traditional search.",
        "loop_desc": "Technical screen → 3-4 onsite rounds (systems, product, ML)",
        "comp_range": "Senior: $350k–$550k | Staff: $500k–$750k",
    },
    {
        "name": "Together AI",
        "slug": "together-ai",
        "ats_type": "greenhouse",
        "board_id": "togetherai",
        "tier": "ai_startup",
        "hq": "San Francisco, CA",
        "size": "100+",
        "logo_url": "https://logo.clearbit.com/together.ai",
        "about": "Decentralized AI cloud. Fast inference, fine-tuning, open models.",
        "loop_desc": "Technical screen → 3 rounds (systems, ML infra, coding)",
        "comp_range": "Senior: $300k–$500k | Staff: $450k–$700k",
    },
    {
        "name": "Anyscale",
        "slug": "anyscale",
        "ats_type": "greenhouse",
        "board_id": "anyscale",
        "tier": "ai_startup",
        "hq": "San Francisco, CA",
        "size": "300+",
        "logo_url": "https://logo.clearbit.com/anyscale.com",
        "about": "Ray framework company. Distributed computing platform for AI workloads.",
        "loop_desc": "Technical screen → 4 onsite rounds (distributed systems, coding, design)",
        "comp_range": "Senior: $300k–$480k | Staff: $450k–$650k",
    },
    {
        "name": "Modal",
        "slug": "modal",
        "ats_type": "ashby",
        "board_id": "modal-labs",
        "tier": "ai_startup",
        "hq": "New York, NY",
        "size": "50+",
        "logo_url": "https://logo.clearbit.com/modal.com",
        "about": "Serverless GPU cloud for AI and data workloads. Python-native infra.",
        "loop_desc": "Technical interview → take-home project → 3 rounds (systems, coding, culture)",
        "comp_range": "Senior: $300k–$500k | Staff: $450k–$700k",
    },
    {
        "name": "Weaviate",
        "slug": "weaviate",
        "ats_type": "greenhouse",
        "board_id": "weaviate",
        "tier": "ai_startup",
        "hq": "Amsterdam, NL",
        "size": "200+",
        "logo_url": "https://logo.clearbit.com/weaviate.io",
        "about": "Open-source vector database for AI applications. RAG and semantic search.",
        "loop_desc": "Technical screen → 3-4 onsite rounds (systems, distributed DB, coding)",
        "comp_range": "Senior: $220k–$350k | Staff: $350k–$500k",
    },
    {
        "name": "Weights & Biases",
        "slug": "weights-biases",
        "ats_type": "greenhouse",
        "board_id": "wandb",
        "tier": "ai_startup",
        "hq": "San Francisco, CA",
        "size": "400+",
        "logo_url": "https://logo.clearbit.com/wandb.ai",
        "about": "MLOps platform. Experiment tracking, model registry, LLM monitoring.",
        "loop_desc": "Recruiter screen → technical screen → 4 onsite rounds",
        "comp_range": "Senior: $260k–$400k | Staff: $380k–$550k",
    },
    {
        "name": "Replit",
        "slug": "replit",
        "ats_type": "greenhouse",
        "board_id": "replit",
        "tier": "ai_startup",
        "hq": "San Francisco, CA",
        "size": "200+",
        "logo_url": "https://logo.clearbit.com/replit.com",
        "about": "AI-native coding environment. Ghostwriter AI, Replit Agent.",
        "loop_desc": "Technical screen → take-home → 3-4 onsite rounds (product-centric)",
        "comp_range": "Senior: $260k–$400k | Staff: $380k–$550k",
    },
    {
        "name": "Cursor",
        "slug": "cursor",
        "ats_type": "ashby",
        "board_id": "anysphere",
        "tier": "ai_startup",
        "hq": "San Francisco, CA",
        "size": "50+",
        "logo_url": "https://logo.clearbit.com/cursor.sh",
        "about": "AI code editor (by Anysphere). Fastest-growing dev tool in history.",
        "loop_desc": "Technical screen → take-home → 3 rounds (product, coding, systems)",
        "comp_range": "Senior: $400k–$700k+ | early-stage upside significant",
    },
    {
        "name": "Character AI",
        "slug": "character-ai",
        "ats_type": "greenhouse",
        "board_id": "characterai",
        "tier": "ai_startup",
        "hq": "Menlo Park, CA",
        "size": "200+",
        "logo_url": "https://logo.clearbit.com/character.ai",
        "about": "Conversational AI platform with personalized AI characters.",
        "loop_desc": "Technical screen → 4 onsite rounds (ML, coding, systems, culture)",
        "comp_range": "Senior: $300k–$500k | Staff: $450k–$700k",
    },
    {
        "name": "ElevenLabs",
        "slug": "elevenlabs",
        "ats_type": "ashby",
        "board_id": "elevenlabs",
        "tier": "ai_startup",
        "hq": "New York, NY",
        "size": "100+",
        "logo_url": "https://logo.clearbit.com/elevenlabs.io",
        "about": "AI voice platform. Text-to-speech, voice cloning, real-time audio.",
        "loop_desc": "Technical screen → take-home → 3-4 rounds (ML audio, systems, coding)",
        "comp_range": "Senior: $280k–$450k | Staff: $420k–$650k",
    },
    {
        "name": "Pika",
        "slug": "pika",
        "ats_type": "ashby",
        "board_id": "pika-labs",
        "tier": "ai_startup",
        "hq": "Palo Alto, CA",
        "size": "50+",
        "logo_url": "https://logo.clearbit.com/pika.art",
        "about": "AI video generation platform. Text-to-video and video editing.",
        "loop_desc": "Technical screen → take-home → 3 rounds",
        "comp_range": "Senior: $300k–$500k+ | pre-IPO equity upside",
    },
    {
        "name": "Harvey",
        "slug": "harvey",
        "ats_type": "ashby",
        "board_id": "harvey",
        "tier": "ai_startup",
        "hq": "San Francisco, CA",
        "size": "100+",
        "logo_url": "https://logo.clearbit.com/harvey.ai",
        "about": "AI for legal services. Document analysis, contract review, legal research.",
        "loop_desc": "Technical screen → 3-4 rounds (product, ML, coding, domain knowledge)",
        "comp_range": "Senior: $280k–$450k | Staff: $420k–$650k",
    },
    {
        "name": "Sierra",
        "slug": "sierra",
        "ats_type": "ashby",
        "board_id": "sierra",
        "tier": "ai_startup",
        "hq": "San Francisco, CA",
        "size": "100+",
        "logo_url": "https://logo.clearbit.com/sierra.ai",
        "about": "AI customer service agents. Founded by ex-Google, Salesforce executives.",
        "loop_desc": "Technical screen → 3-4 rounds (systems, coding, ML infra)",
        "comp_range": "Senior: $300k–$500k | Staff: $450k–$700k",
    },
    {
        "name": "Cognition",
        "slug": "cognition",
        "ats_type": "ashby",
        "board_id": "cognition-labs",
        "tier": "ai_startup",
        "hq": "San Francisco, CA",
        "size": "50+",
        "logo_url": "https://logo.clearbit.com/cognition.ai",
        "about": "Creator of Devin, the AI software engineer. Applied AI coding agents.",
        "loop_desc": "Technical screen → take-home → 3 rounds (systems, agent design, coding)",
        "comp_range": "Senior: $400k–$700k+ | very early equity upside",
    },
    {
        "name": "LangChain",
        "slug": "langchain",
        "ats_type": "greenhouse",
        "board_id": "langchain",
        "tier": "ai_startup",
        "hq": "San Francisco, CA",
        "size": "100+",
        "logo_url": "https://logo.clearbit.com/langchain.com",
        "about": "LLM application framework and LangSmith observability platform.",
        "loop_desc": "Technical screen → take-home → 3-4 rounds (product, coding, open-source)",
        "comp_range": "Senior: $260k–$420k | Staff: $380k–$580k",
    },

    # ── YC Alumni & High-Growth Unicorns ─────────────────────────────────────
    {
        "name": "Stripe",
        "slug": "stripe",
        "ats_type": "greenhouse",
        "board_id": "stripe",
        "tier": "yc_unicorn",
        "hq": "San Francisco, CA",
        "size": "8,000+",
        "logo_url": "https://logo.clearbit.com/stripe.com",
        "about": "Global payments infrastructure. YC W10. $95B valuation. Powers millions of businesses.",
        "loop_desc": "Phone screen → 2 technical rounds → onsite (coding, system design, debugging exercise)",
        "comp_range": "Senior: $350k–$500k | Staff: $500k–$750k",
    },
    {
        "name": "Databricks",
        "slug": "databricks",
        "ats_type": "greenhouse",
        "board_id": "databricks",
        "tier": "yc_unicorn",
        "hq": "San Francisco, CA",
        "size": "6,000+",
        "logo_url": "https://logo.clearbit.com/databricks.com",
        "about": "Data & AI platform. $62B valuation. Unified analytics on Spark and Delta Lake.",
        "loop_desc": "Phone screen → 4-5 onsite rounds (coding, distributed systems, ML infra, culture)",
        "comp_range": "Senior: $350k–$500k | Staff: $500k–$750k",
    },
    {
        "name": "Plaid",
        "slug": "plaid",
        "ats_type": "greenhouse",
        "board_id": "plaid",
        "tier": "yc_unicorn",
        "hq": "San Francisco, CA",
        "size": "1,000+",
        "logo_url": "https://logo.clearbit.com/plaid.com",
        "about": "Financial data network. YC W13. $13.4B valuation. Connects apps to bank accounts.",
        "loop_desc": "Recruiter screen → technical screen → 3-4 onsite (coding, system design, API design)",
        "comp_range": "Senior: $300k–$450k | Staff: $450k–$650k",
    },
    {
        "name": "Rippling",
        "slug": "rippling",
        "ats_type": "greenhouse",
        "board_id": "rippling",
        "tier": "yc_unicorn",
        "hq": "San Francisco, CA",
        "size": "3,000+",
        "logo_url": "https://logo.clearbit.com/rippling.com",
        "about": "HR, IT & Finance platform. $13.5B valuation. Automates employee lifecycle.",
        "loop_desc": "Technical screen → 3-4 onsite rounds (coding, system design, product sense)",
        "comp_range": "Senior: $300k–$450k | Staff: $450k–$650k",
    },
    {
        "name": "Brex",
        "slug": "brex",
        "ats_type": "greenhouse",
        "board_id": "brex",
        "tier": "yc_unicorn",
        "hq": "San Francisco, CA",
        "size": "1,200+",
        "logo_url": "https://logo.clearbit.com/brex.com",
        "about": "Corporate cards & spend management. YC W17. $12B valuation. CFO stack for startups.",
        "loop_desc": "Recruiter screen → 2 technical rounds → onsite (coding, systems, culture)",
        "comp_range": "Senior: $280k–$420k | Staff: $400k–$600k",
    },
    {
        "name": "Notion",
        "slug": "notion",
        "ats_type": "greenhouse",
        "board_id": "notion",
        "tier": "yc_unicorn",
        "hq": "San Francisco, CA",
        "size": "500+",
        "logo_url": "https://logo.clearbit.com/notion.so",
        "about": "Collaborative workspace & wiki. YC W18. $10B valuation. Docs, databases, AI.",
        "loop_desc": "Recruiter screen → take-home project → 3-4 onsite (coding, systems, product thinking)",
        "comp_range": "Senior: $280k–$420k | Staff: $400k–$600k",
    },
    {
        "name": "Linear",
        "slug": "linear",
        "ats_type": "ashby",
        "board_id": "linear",
        "tier": "yc_unicorn",
        "hq": "San Francisco, CA",
        "size": "100+",
        "logo_url": "https://logo.clearbit.com/linear.app",
        "about": "Project management for dev teams. YC S19. Fast, keyboard-first issue tracker.",
        "loop_desc": "Async take-home → 3 rounds (product taste, systems, coding quality)",
        "comp_range": "Senior: $300k–$500k | pre-IPO equity significant",
    },
    {
        "name": "Vercel",
        "slug": "vercel",
        "ats_type": "ashby",
        "board_id": "vercel",
        "tier": "yc_unicorn",
        "hq": "San Francisco, CA",
        "size": "500+",
        "logo_url": "https://logo.clearbit.com/vercel.com",
        "about": "Frontend cloud platform. $3.25B valuation. Creators of Next.js.",
        "loop_desc": "Technical screen → take-home → 3 rounds (systems, coding, product)",
        "comp_range": "Senior: $280k–$450k | Staff: $400k–$650k",
    },
    {
        "name": "Supabase",
        "slug": "supabase",
        "ats_type": "ashby",
        "board_id": "supabase",
        "tier": "yc_unicorn",
        "hq": "San Francisco, CA",
        "size": "200+",
        "logo_url": "https://logo.clearbit.com/supabase.com",
        "about": "Open-source Firebase alternative. YC S20. $2B valuation. Postgres-first backend.",
        "loop_desc": "Async screen → 3 rounds (coding, systems, open-source culture). Fully remote.",
        "comp_range": "Senior: $200k–$350k + equity | remote-first globally distributed",
    },
    {
        "name": "Discord",
        "slug": "discord",
        "ats_type": "greenhouse",
        "board_id": "discord",
        "tier": "yc_unicorn",
        "hq": "San Francisco, CA",
        "size": "600+",
        "logo_url": "https://logo.clearbit.com/discord.com",
        "about": "Gaming & community chat platform. YC S15. $15B valuation. 600M+ registered users.",
        "loop_desc": "Recruiter screen → technical screen → 3-4 onsite (coding, systems, culture fit)",
        "comp_range": "Senior: $280k–$420k | Staff: $400k–$600k",
    },
    {
        "name": "Ramp",
        "slug": "ramp",
        "ats_type": "greenhouse",
        "board_id": "ramp",
        "tier": "yc_unicorn",
        "hq": "New York, NY",
        "size": "800+",
        "logo_url": "https://logo.clearbit.com/ramp.com",
        "about": "Corporate finance platform. YC W19. $7.65B valuation. Expense management & cards.",
        "loop_desc": "Technical screen → 2-3 rounds (coding, system design, product sense)",
        "comp_range": "Senior: $280k–$430k | Staff: $420k–$600k",
    },
    {
        "name": "Airtable",
        "slug": "airtable",
        "ats_type": "greenhouse",
        "board_id": "airtable",
        "tier": "yc_unicorn",
        "hq": "San Francisco, CA",
        "size": "800+",
        "logo_url": "https://logo.clearbit.com/airtable.com",
        "about": "Low-code platform for business apps. YC S15. $11B valuation. Spreadsheet meets DB.",
        "loop_desc": "Technical screen → take-home → 3-4 onsite (product, coding, system design)",
        "comp_range": "Senior: $280k–$420k | Staff: $400k–$580k",
    },
]
